# source this

# UNIFYFS job setup
unset UNIFYFS_INSTALL
unset UNIFYFS_BINDIR
unset UNIFYFS_LIBDIR

# set optional UnifyFS config environ here
unset UNIFYFS_SERVER_CORES
unset UNIFYFS_SHAREDFS_DIR
unset UNIFYFS_LOG_DIR
unset UNIFYFS_LOG_ON_ERROR
unset UNIFYFS_LOG_VERBOSITY

unset UNIFYFS_LOGIO_CHUNK_SIZE
unset UNIFYFS_LOGIO_SHMEM_SIZE
unset UNIFYFS_LOGIO_SPILL_SIZE
unset UNIFYFS_LOGIO_SPILL_DIR

